version: '3'
services:
  web:
    build: .
    command: bash start.sh
    container_name: web-milababies
    volumes:
      - .:/var/www/milababies
    ports:
      - 3000:3000
    links:
      - db
    env_file:
      - .env.docker
  db:
    image: postgres:10.3-alpine
    container_name: db-milababies
    hostname: db-milababies
    ports:
      - 0:5432
    env_file:
      .env.docker
    volumes:
      - milababies-data:/var/lib/postgresql/data
volumes:
  milababies-data:
